// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// narrowsqlite3.cpp
cpp11::sexp sqlite_cpp_open(std::string filename);
extern "C" SEXP _narrowsqlite3_sqlite_cpp_open(SEXP filename) {
  BEGIN_CPP11
    return cpp11::as_sexp(sqlite_cpp_open(cpp11::as_cpp<cpp11::decay_t<std::string>>(filename)));
  END_CPP11
}
// narrowsqlite3.cpp
void sqlite_cpp_close(cpp11::sexp con_sexp);
extern "C" SEXP _narrowsqlite3_sqlite_cpp_close(SEXP con_sexp) {
  BEGIN_CPP11
    sqlite_cpp_close(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(con_sexp));
    return R_NilValue;
  END_CPP11
}
// narrowsqlite3.cpp
int sqlite_cpp_exec(cpp11::sexp con_sexp, std::string sql);
extern "C" SEXP _narrowsqlite3_sqlite_cpp_exec(SEXP con_sexp, SEXP sql) {
  BEGIN_CPP11
    return cpp11::as_sexp(sqlite_cpp_exec(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(con_sexp), cpp11::as_cpp<cpp11::decay_t<std::string>>(sql)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_narrowsqlite3_sqlite_cpp_close", (DL_FUNC) &_narrowsqlite3_sqlite_cpp_close, 1},
    {"_narrowsqlite3_sqlite_cpp_exec",  (DL_FUNC) &_narrowsqlite3_sqlite_cpp_exec,  2},
    {"_narrowsqlite3_sqlite_cpp_open",  (DL_FUNC) &_narrowsqlite3_sqlite_cpp_open,  1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_narrowsqlite3(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
