# Generated by cpp11: do not edit by hand

gpkg_cpp_open <- function(filename) {
  .Call(`_gpkg_gpkg_cpp_open`, filename)
}

gpkg_cpp_close <- function(con_sexp) {
  invisible(.Call(`_gpkg_gpkg_cpp_close`, con_sexp))
}

gpkg_cpp_exec <- function(con_sexp, sql) {
  .Call(`_gpkg_gpkg_cpp_exec`, con_sexp, sql)
}

gpkg_cpp_query <- function(con_sexp, sql, array_data_xptr, schema_xptr) {
  invisible(.Call(`_gpkg_gpkg_cpp_query`, con_sexp, sql, array_data_xptr, schema_xptr))
}

gpkg_cpp_query2 <- function(con_sexp, sql, array_data_xptr, schema_xptr) {
  invisible(.Call(`_gpkg_gpkg_cpp_query2`, con_sexp, sql, array_data_xptr, schema_xptr))
}
